# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1888ae6c1822e78dcc41fdfd37b384ed5a0fefaf49f811f01d5266cd0c7978e63baa71c29e07190bb6b87bfe8087d12ce69fe7c37732128f041c67e58e779ae

test:
  secret_key_base: e4e083020615fdca0ff4945668422949a92503be90da4ec75b0b81dac9b5ff475982a0f5defce33bd7adf0eed77cb89c78cc4dfee3f19553d924431c17fb0d5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
